# Generated by Django 3.0.6 on 2020-05-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('business_type', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images', models.FileField(upload_to='Business/Images/')),
                ('certificate', models.FileField(upload_to='Business/Certificate/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'Business',
            },
        ),
    ]
