# Generated by Django 3.0.6 on 2020-05-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('lender_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('images', models.FileField(upload_to='lender/Images/')),
                ('certificate', models.FileField(upload_to='lender/Certificate/')),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'lender',
                'verbose_name_plural': 'Lenders',
                'db_table': 'lender',
            },
        ),
    ]
