# Generated by Django 3.0.6 on 2020-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
