# Generated by Django 3.0.6 on 2020-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lender_is_lender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='loans',
            field=models.ManyToManyField(to='app.Loan'),
        ),
        migrations.AddField(
            model_name='lender',
            name='loan_requests',
            field=models.ManyToManyField(to='app.Loan'),
        ),
        migrations.AlterField(
            model_name='lender',
            name='is_lender',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
